name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:

    runs-on: ubuntu-latest
    container: 
      image: node

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
#    - name: Build the .net core solution
#      run: dotnet publish --configuration Release -o pub
      
  cd:
    
    runs-on: ubuntu-latest
    needs: [ci]
    
    steps:    
    - uses: actions/checkout@v2
    - name: Dockerhub login
      run: docker login docker.io/library -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the docker image and tag it
      run: docker build . -t device-service
    - name: Push the docker image to dockerhub
      run: docker push device-service
